sonatype/nexus-book

site/book-template.html
Reformat included. View non-whitespace changes https://github.com/sonatype/nexus-book/pull/34/files?w=1.
=> Remove unused HTML attribute.

chapter-smartproxy.asciidoc
I believe this correction is right, please check.
=> Server correction

chapter-clm.asciidoc, chapter-community.asciidoc, chapter-configuration.asciidoc, chapter-copyright.asciidoc, chapter-eval.asciidoc, chapter-introduction.asciidoc, chapter-ldap.asciidoc, chapter-staging.asciidoc, chapter-using-nexus-ui.asciidoc, docbook-xsl/custom-chunked.xsl
Input and fixes in the branch welcome.
Chapter 2 (intro to repo mgt and clm) has not yet been converted.
=> WIP: Nexus everywhere

chapter-configuration.asciidoc
https://issues.sonatype.org/browse/NEXUS-8508
=> Minimal documentation for Bundles, NEXUS-8508

chapter-maven.asciidoc
https://issues.sonatype.org/browse/NEXUS-8530
At this stage this chapter referenced the nexus-book-examples repo. I think we will have to create a Nexus 3 branch there now and update all the examples to work against Nexus 3 with CMA. That is also going to be a good test.
Please let me know if you agree on this approach and if so I can get this work included as part of this issue and respectively also update the PR with new wording.
=> Updated tool configs to new CMA repos

chapter-configuration.asciidoc
For review:
First word, I believe might be the wrong word but not 100% confident about the word change.
Second word, I believe is wrong because the field before it is required so it's not instead.
=> Word changes

chapter-configuration.asciidoc
https://issues.sonatype.org/browse/NEXUS-8515
=> Rebuild Maven Repository Metadata task docs

book-nexus.asciidoc, chapter-installation.asciidoc
https://issues.sonatype.org/browse/NEXUS-8822
=> Minimal install docs

chapter-configuration.asciidoc, chapter-installation.asciidoc, chapter-using-plugins.asciidoc, nexus-book-declarations.asciidoc
https://issues.sonatype.org/browse/NEXUS-8901
=> Updated version strings to 2.11.4-01

chapter-configuration.asciidoc, chapter-staging.asciidoc
Signed-off-by: Anders Hammar <anders@hammar.net>
=> Corrected some text typos.

chapter-nuget.asciidoc
I was rereviewing this against VS2015 and do not believe we updated some of the words when we updated the screenshot for VS2013.
No further updates need to be done against VS2015 but added some clarification overall.
=> Integration with VS (16.8) text updates

chapter-docker.asciidoc, chapter-security.asciidoc
https://issues.sonatype.org/browse/NEXUS-9041
CI builds with rendered results are available on Bamboo at  http://bamboo.s/browse/BOOK-NEXUS33
Check the Artifacts - site for a specific build (preferably latest...):
http://bamboo.s/browse/BOOK-NEXUS33-10/artifact/STAGE/site/3.0/reference/docker.html
=> WIP: Docker documentation

chapter-configuration.asciidoc, chapter-installation.asciidoc, chapter-introduction.asciidoc, chapter-smartproxy.asciidoc
Work on https://issues.sonatype.org/browse/NEXUS-9223 - removal of sonatype-work references from NX3 documentation.
Bamboo: http://bamboo.s/browse/BOOK-NEXUS44
=> Removal of sonatype-work

chapter-npm.asciidoc
Issue: https://issues.sonatype.org/browse/NEXUS-9239
=> Add deprecate instructions to npm chapter

chapter-configuration.asciidoc
Includes:
* Section within proxies for buttons that can be used for future buttons as well as this one
* Presence of the invalidate negative cache button and description
https://issues.sonatype.org/browse/NEXUS-9019
=> NEXUS-9019 Adding the invalidate negative cache button

chapter-configuration.asciidoc
Includes:
* Word change recommended from https://github.com/sonatype/nexus-book/pull/88
* Addition of button and description in proxy button list
https://issues.sonatype.org/browse/NEXUS-9018
=> NEXUS-9018 Documenting invalidate proxy cache button

chapter-configuration.asciidoc
https://issues.sonatype.org/browse/NEXUS-9022
Not sure if we want to say more or not.  Speak your piece or hold your peace?=)
=> NEXUS-9022 Documentation of proxy repository index button

chapter-configuration.asciidoc, chapter-docker.asciidoc
https://issues.sonatype.org/browse/NEXUS-9378
Includes
- doc for context path 
- registry api V1 flag
- scheduled task
=> Docker documentation update for M6 release

chapter-configuration.asciidoc
https://issues.sonatype.org/browse/NEXUS-9233
=> added storage facet to repo mgt docs, 

chapter-configuration.asciidoc
Already uses the new wording from https://github.com/sonatype/nexus-internal/pull/300
https://issues.sonatype.org/browse/NEXUS-9386
Rendered output at http://bamboo.s/browse/BOOK-NEXUS59-2/artifact/STAGE/site/3.0/reference/admin.html#admin-repository-blobstores
=> Documentation for blob store administration

chapter-configuration.asciidoc
https://issues.sonatype.org/browse/NEXUS-9448
=> NEXUS-9448: Update Nexus 3 documentation to include "Purge Unused Maven Snapshots" task

chapter-npm.asciidoc
…logging and syntax, NEXUS-9318
https://issues.sonatype.org/browse/NEXUS-9318
=> Improved npm install docs and security

chapter-security.asciidoc
Depends on https://github.com/sonatype/nexus-internal/pull/333
=> NEXUS-8449 - Update jetty xml configuration options as it pertains to https

chapter-configuration.asciidoc
See https://issues.sonatype.org/browse/NEXUS-9619
=> added description for Purge Orphaned API Keys task, NEXUS-9619

chapter-configuration.asciidoc
https://issues.sonatype.org/browse/NEXUS-9460
=> added minimal documentation for Maven index tasks, NEXUS-9460

chapter-configuration.asciidoc
https://issues.sonatype.org/browse/NEXUS-9653
Rendered output at http://bamboo.s/browse/BOOK-NEXUS78
=> Document Compact blob store task

chapter-configuration.asciidoc, chapter-docker.asciidoc
https://issues.sonatype.org/browse/NEXUS-9709
=> Updated task names

chapter-configuration.asciidoc, chapter-maven.asciidoc, chapter-nuget.asciidoc
https://issues.sonatype.org/browse/NEXUS-9232
Just moving things around really. Not worth a review. PR here just fyi @dulanism
=> Moved facet/format specific docs into related chapters

chapter-configuration.asciidoc, chapter-installation.asciidoc, chapter-security.asciidoc
to various appropriate places in docs
https://issues.sonatype.org/browse/NEXUS-9743
=> added default admin username and password 

chapter-docker.asciidoc
https://issues.sonatype.org/browse/NEXUS-9664
=> Tips section for SSL certificate usage

book-nexus.asciidoc, chapter-bower.asciidoc
This chapter is not ready for review yet.
Bamboo build: http://bamboo.s/browse/BOOK-NEXUS83
https://issues.sonatype.org/browse/NEXUS-9580
https://issues.sonatype.org/browse/NEXUS-9582
=> WIP - Bower chapter

chapter-installation.asciidoc
for for jvm memory, port, context and data directory.
https://issues.sonatype.org/browse/NEXUS-9707
Rendered results at http://bamboo.s/browse/BOOK-NEXUS88
This one is for you @aavritzer ;-)
=> Added short config tips 

chapter-repository-health-check.asciidoc
Quick change to the sentence to make more sense. This is for the Kaos team.
https://issues.sonatype.org/browse/CLM-6018
Associated edits:
http://bamboo.s/browse/BOOK-NEXUS2-234
http://bamboo.s/browse/BOOK-NEXUS-388
=> Quick fix osvdb sentence

book-nexus.asciidoc, chapter-bower.asciidoc
Created for @dulanism to update .. 
Rendered results at http://bamboo.s/browse/BOOK-NEXUS87
=> More bower related documentation

chapter-installation.asciidoc
https://issues.sonatype.org/browse/NEXUS-9765
=> Remove ref to karaf.instances

build.sh, chapter-bower.asciidoc, chapter-using-nexus-ui.asciidoc
Add Hosted and Group Repo entries to bower doc
CI: http://bamboo.s/browse/BOOK-NEXUS94
JIRA: https://issues.sonatype.org/browse/NEXUS-9579
https://issues.sonatype.org/browse/NEXUS-9581
=> Add Hosted and Group Repo entries to bower doc

chapter-bundle-dev.asciidoc
On scan of new section (RE: NEXUS-9757).
I am confident the above are typos but not 100% confident that my fixes are correct so making a PR rather than just merging.  Would appreciate a +1.
=> Typo fixes

book-nexus.asciidoc, chapter-scripting.asciidoc
Issue https://issues.sonatype.org/browse/NEXUS-9758
CI build at http://bamboo.s/browse/BOOK-NEXUS95
References example scripts are in https://github.com/sonatype/nexus-book-examples/tree/nexus-3.0.x/scripting - please also review those. Feel free to commit improvements there straight to the branch.
=> Provisioning scripts

chapter-concepts.asciidoc
Just a short section to explain the concepts around what an "asset" is and how it relates to the components. This came up as an issue from some user feedback.
Issue: https://issues.sonatype.org/browse/NEXUS-9835
CI plan with rendered results: http://bamboo.s/browse/BOOK-NEXUS97-1
=> Nexus 9835 assets

chapter-security.asciidoc
https://issues.sonatype.org/browse/NEXUS-9876
Also removed 2nd newline at end.
http://bamboo.s/browse/BOOK-NEXUS103-1
=> NEXUS-9876-fix

chapter-npm.asciidoc, chapter-nuget.asciidoc, chapter-repository-health-check.asciidoc
CI http://bamboo.s/browse/BOOK-NEXUS102
JIRA https://issues.sonatype.org/browse/NEXUS-9860
* Branch refers to the revision as 2.13; this edit is actually for the 2.12.1 release
=> RHC section revisions

chapter-docker.asciidoc
JIRA https://issues.sonatype.org/browse/NEXUS-9870
CI http://bamboo.s/browse/BOOK-NEXUS112
=> Docker SSL and repo config updates

chapter-installation.asciidoc
JIRA https://issues.sonatype.org/browse/NEXUS-9851
=> Establish section for service config

chapter-installation.asciidoc
Updated docs for @kellyrob99's changes.
=> NEXUS-9964: Increase default max heap for Nexus

chapter-scripting.asciidoc
added quotes around keys, changed to curly brackets
=> Json format fix

chapter-installation.asciidoc
JIRA: https://issues.sonatype.org/browse/NEXUS-10043 (see feedback in comments)
Related to: https://issues.sonatype.org/browse/NEXUS-9859
CI: http://bamboo.s/browse/BOOK-NEXUS123
=> Usage of a Docker image to Install NX3 (dockerhub)

chapter-scripting.asciidoc
- add clarity around return values and offer some assistance with how to construct XML/JSON responses
Related to https://github.com/sonatype/nexus-book-examples/pull/2
=> NEXUS-10061 - Integration API return values

chapter-installation.asciidoc
Updated CentOS/Redhat section for systemd user; more commonly used.
=> Update centos-redhat config section

chapter-pypi.asciidoc
JIRA: https://issues.sonatype.org/browse/NEXUS-9826
=> PyPI proxy documentation

chapter-configuration.asciidoc
JIRA: https://issues.sonatype.org/browse/NEXUS-9996
https://issues.sonatype.org/browse/NEXUS-9999
License upload and active user management
=> Added updated license section with managing active lic users

build.sh, chapter-pypi.asciidoc
CI: http://bamboo.s/browse/BOOK-NEXUS135
JIRA https://issues.sonatype.org/browse/NEXUS-9826
=> PyPI configuration for proxy - extended

chapter-using-nexus-ui.asciidoc
Some typo fixes but also mostly for clarity.
Please be brutal with feedback.  If you think this is less clear, I can trash this PR, but I definitely think this section can be improved so trying.
https://issues.sonatype.org/browse/NEXUS-10153
http://bamboo.s/browse/BOOK-NEXUS137-1
=> NEXUS-10153 User Button rewrite

chapter-pypi.asciidoc
https://issues.sonatype.org/browse/NEXUS-9825
http://bamboo.s/browse/BOOK-NEXUS136
Will also include group https://issues.sonatype.org/browse/NEXUS-9827
=> NEXUS-9825 Pypi hosted configuration

book-nexus.asciidoc, chapter-migration.asciidoc
This is a pre-doc outline / walkthru of the migration UI
CI: http://bamboo.s/browse/BOOK-NEXUS140
JIRA: https://issues.sonatype.org/browse/NEXUS-10173
=> Migration documentation initial

book-nexus.asciidoc, chapter-rubygems.asciidoc
Trivial: New RubyGems chapter and TOC for 3.1
=> Added rubygems chapter and toc entry

chapter-pypi.asciidoc
JIRA https://issues.sonatype.org/browse/NEXUS-9827
CI http://bamboo.s/browse/BOOK-NEXUS141
* includes SSL self-signed certificate setup
=> NEXUS-9827-pypi group repository

chapter-configuration.asciidoc
JIRA - https://issues.sonatype.org/browse/NEXUS-10117
CI - TBD
=> OSS-PAID bundle docs

chapter-migration.asciidoc
JIRA: https://issues.sonatype.org/browse/NEXUS-10222
CI: http://bamboo.s/browse/BOOK-NEXUS146
=> NEXUS-10222 Pre-migration steps for migration manual 

chapter-installation.asciidoc
Based around review a while ago.  Not associated with any ticket.
Will cherry pick to 3.1.x on merge as well once approved.
http://bamboo.s/browse/BOOK-NEXUS148-1
=> Tip add and typo fixes

README.asciidoc, chapter-best-practices.asciidoc, chapter-community.asciidoc, chapter-concepts.asciidoc, chapter-configuration.asciidoc, chapter-crowd.asciidoc, chapter-eval.asciidoc, chapter-installation.asciidoc, chapter-introduction.asciidoc, chapter-maven-settings.asciidoc, chapter-migrating.asciidoc, chapter-obr.asciidoc, chapter-p2.asciidoc, chapter-procurement.asciidoc, chapter-repository-health-check.asciidoc, chapter-rubygems.asciidoc, chapter-ssl.asciidoc, chapter-using-nexus-ui.asciidoc, chapter-using-plugins.asciidoc, chapter-yum.asciidoc, nexus-book-declarations.asciidoc
=> refactor of usage of pro and new nxrm macro

README.asciidoc, chapter-bundle-dev.asciidoc, chapter-configuration.asciidoc, chapter-contributing.asciidoc, chapter-docker.asciidoc, chapter-installation.asciidoc, chapter-maven.asciidoc, chapter-nuget.asciidoc, chapter-preface.asciidoc, chapter-raw.asciidoc, chapter-repository-health-check.asciidoc, chapter-scripting.asciidoc, index.asciidoc, nexus-book-declarations.asciidoc
also commented out license section since its a 3.1 feature and I dont know how it got here the first place. 
Some minor other cosmetic fixes.
fyi @dulanism @annrollo @jwayman
=> Refactored usage of pro after intro of nxrm

chapter-scripting.asciidoc
also cherry picked to 3.1. branch
=> docs for expanded scripting examples

chapter-migration.asciidoc
JIRA: https://issues.sonatype.org/browse/NEXUS-10173 & https://issues.sonatype.org/browse/NEXUS-10222 - Combining UI & pre-migration docs after preliminary docs for pre-migration were already merged (i.e. https://github.com/sonatype/nexus-book/pull/182)
**Note: the {pro} macro will be replaced with a new macro {nxrm} though the latter was created after this branch existed. I'll refine the proper macros after merge.**
CI: http://bamboo.s/browse/BOOK-NEXUS144
=> NEXUS-10173 & NEXUS 10222 pre migration & UI docs

chapter-contributing.asciidoc
The most trivial of the trivials.
=> Adding Jeffry Hesse as a contributor

chapter-installation.asciidoc, chapter-using-nexus-ui.asciidoc
After some contact from a German speaking user via email I fixed up the reverse proxy section a bit and added a link regarding the data directory.
=> User contributions

nexus-book-declarations.asciidoc
Temporarily updated to nexus book version - From 3.0.0/3.0.0-03 to 3.0.1/3.0.1-01, ahead of release
=> NEXUS-10404-book-declarations

chapter-pypi.asciidoc
Based around recent experiences personal and with beta tester.
=> Adding tip to use SSL w/ pip

chapter-upgrading.asciidoc
JIRA: https://issues.sonatype.org/browse/NEXUS-10398
CI: http://bamboo.s/browse/BOOK-NEXUS166
- Add repo target entry to Repositories ( in Content section of the wizard)
- Incorporate/explain repo target as a supported format
=> NEXUS-10398-repo-target-content

chapter-security.asciidoc
JIRA: https://issues.sonatype.org/browse/NEXUS-10303
CI: http://bamboo.s/browse/BOOK-NEXUS160
=> NEXUS-10303 Port and adapt user token security chapter to 3.1

chapter-upgrading.asciidoc
based around changes to Simplify Migration URL defined in
https://issues.sonatype.org/browse/NEXUS-10367
I made a slightly tangential wording change to have the two sentences
in this section match better.
CI: http://bamboo.s/browse/BOOK-NEXUS168-1
=> NEXUS-10367 Adjustments to Agent Connection section

chapter-raw.asciidoc
To help prompt people not to copy paste over their existing servers (and potentially mess up other stuff).
No JIRA ticket, just a thought based on internal work.
=> Configuration clarify

chapter-repository-health-check.asciidoc, chapter-upgrading.asciidoc
JIRA: https://issues.sonatype.org/browse/NEXUS-10075
CI: http://bamboo.s/browse/BOOK-NEXUS173
Also will mention the SSL:Health Check capability in NX2 pro
=> NEXUS-10075-RHC-migration

chapter-upgrading.asciidoc
From https://github.com/sonatype/nexus-internal/pull/937 (already merged)
=> dulanism-patch-empty-group-upgrade

chapter-upgrading.asciidoc
https://issues.sonatype.org/browse/NEXUS-10380
* Added to list
* Added section of guidance of wisdom of upgrading both at once
NOTE: I did not see a need to specifically mention the second
acceptance criteria from the ticket.  If folks believe it is noteworthy
I can make that adjustment.
=> NEXUS-10380-Upgrade-Target-Privileges

chapter-upgrading.asciidoc
JIRA: https://issues.sonatype.org/browse/NEXUS-10659
Notes:
- Cherry pick these changes into @jwayman's branch
- Added 'Health Check' to the list of Repository content that can be upgraded (see 'Upgrading Content')
- Added 'Crowd' config as s 'Content' option
=> NEXUS-10659-iq-server-upgrade

chapter-installation.asciidoc
JIRA: https://issues.sonatype.org/browse/NEXUS-10425
CI: TBD
- Also includes fix to wrong config in the ProxyPassReverse line from the Apache httpd in the 3.0 book.
- Cherry pick/rebase changes to nexus-3.1.x branch
=> NEXUS-10425-nginx-docs-patch

chapter-upgrading.asciidoc
https://issues.sonatype.org/browse/NEXUS-10482
=> [NEXUS-10482] rename migration to upgrade

chapter-installation.asciidoc
Also, line break fixes
JIRA: https://issues.sonatype.org/browse/NEXUS-10664
=> NEXUS-10664-systemd-correction

chapter-installation.asciidoc, chapter-upgrading.asciidoc
Please give it a read @dulanism and ping me for questions. We can go it change by change if necessary. There are numerous fixes and changes of varying impact in terms of complexity. I suggest to just build it locally and read the chapter (and the linked section in the install chapter). If it makes more sense than the prior version in your understanding... we should merge.
=> Upgrade guide fixes

book-nexus.asciidoc, chapter-high-availability.asciidoc
JIRA: https://issues.sonatype.org/browse/NEXUS-10617
CI: http://bamboo.s/browse/BOOK-NEXUS174
=> High-Availability-chapter

chapter-high-availability.asciidoc
JIRA: https://issues.sonatype.org/browse/NEXUS-10617
CI: http://bamboo.s/browse/BOOK-NEXUS193
=> [NEXUS-10617] ha-config-startup
