chapter-configuration.asciidoc
The testguide specifically says you cannot assign privileges to users, that you have to assign the privilidges to a role which then you can assign to a user.  My test of this showed this to be true.  While just a wording difference, I think not having privilege lessens the chance of confusion and IMO is better than the alternative which would be to explain this verbosely.
=> Suggested strike+

chapter-smartproxy.asciidoc
I know we've talked about this and believe the conclusion was that locational references need to be paper/web unspecific which I do not believe the word "above" is.  I've genericized but since unsure making a PR.
=> Remove reference to location

chapter-maven.asciidoc
I believe either the letter a is redundant or there is a word missing.  Sending PR to assure I'm right and I picked the right fix.
I noticed this reviewing the NX3 book draft btw.
=> Remove redundant letter

chapter-ssl.asciidoc
mainly we wanted to nuke import-ssl but I cleaned up a bunch of other stuff. We have a comprehensive article in the KB now for keytool commands.
=> rewrite ssl chapter and simplify

chapter-installation.asciidoc, chapter-security.asciidoc
* Adjusted references from custom.properties to org.sonatype.nexus.cfg
(NEXUS-9337)
* Removed the example link to 2.5 from 5.8.4 as there is no example
there (just a list of files).  If an example is added, we could addback
this link, currently I believe deceiving.
* Tightened some spacing to match styleguide
https://issues.sonatype.org/browse/NEXUS-9337
CI: http://bamboo.s/browse/BOOK-NEXUS52
=> NEXUS-9337 Adjusted references regarding SSL creation

chapter-configuration.asciidoc
https://issues.sonatype.org/browse/NEXUS-9443
(We need to wait on https://issues.sonatype.org/browse/NEXUS-9182 to merge.)
=> NEXUS-9443: Update documentation to reflect single-button "Invalidate cache" action for repositories

chapter-docker.asciidoc
In m6 you need to login before you can perform any actions against hosted/proxy repositories.  This invalidates the docker authentication section as written as you are no longer prompted (NEXUS-9374).
Creating a PR rather than committing directly since a larger revamp.
This section was also adjusted to "size 114" tho probably don't notice since almost totally rewritten.
=> Rewrite based on NEXUS-9374 decision

site/css/clmBook.css
An example url:
http://books.sonatype.com/nexus-book/3.0/reference/security.html#ssl-inbound
Before:
After:
=> fix hidden anchor link titles

chapter-concepts.asciidoc, chapter-configuration.asciidoc, chapter-maven.asciidoc
Similar to NPM, Docker and NuGet chapters this now talks about all aspects of the Maven repository format and not just the client tool configuration.
Covers the implementation of the following issues:
https://issues.sonatype.org/browse/NEXUS-9234
https://issues.sonatype.org/browse/NEXUS-9445
https://issues.sonatype.org/browse/NEXUS-9123
https://issues.sonatype.org/browse/NEXUS-9232 (as applicable for the Maven format)
Review for this PR should include reading the whole Maven chapter paying specific attention to topics covered by the linked issues and whatever was changed in the client tool related docs.
Check out the latest rendered results on Bamboo:
http://bamboo.s/browse/BOOK-NEXUS76
=> Revamped Maven repository chapter

chapter-maven.asciidoc
Issue: https://issues.sonatype.org/browse/OSSRH-19926
Related: https://github.com/sonatype/nexus-book/pull/119
This string should never change, regardless of branding, as third-party clients depend on it. As a result, I’ve changed it from the {pro} macro to a static string.
=> [OSSRH-1992] Change credentials to static string to avoid breaking clients

chapter-npm.asciidoc
* I corrected a - count which seemed ok in the published book but was causing the preview in github to have block text and normal text inverted
* I made an adjustment to the resultant .npmrc to clarify confusion noticed in https://issues.sonatype.org/browse/NEXUS-9829
=> Minor fixes

chapter-nuget.asciidoc
Remove double dot from sentence: 
`A typical, useful example would be to group the proxy repository that proxies the NuGet Gallery, a NuGet, hosted repository with internal software packages and another NuGet, hosted repository with third-party packages..`
=> Fixes typo described in #144

chapter-docker.asciidoc
Based on entire chapter review  after NEXUS-9777 work was completed to make sure no side affects as advertised.
Being NEXUS-9777 is already closed and this is my own initiative, there is no correctsponding JIRA ticket for this.
Mostly typo fixes however three more serious rewrites of note (none of which were affects from NEXUS-9777 as far as I can tell):
* The previous write suggests you do not enable v1 except in certain circumstances.  I have never agreed with this nor do I see harm in enabling it (it acts as fallback from v2, so no additional failures would be caused; if v2 and v1 fails, you're no worse off than if v2 fails & if v2 works v1 is never hit) so I rewrote the section to clarify if people are unsure they should enable it.  I hope this helps get less support and community …
=> Docker chapter improvements

chapter-repository-health-check.asciidoc
To avoid the confusion for those who may take the statement to mean
that we supply security and license data for docker images (real use
case).
=> Updated sentence to affirm RHC only provides security for components that Sonatype supports

chapter-preface.asciidoc
This is a minor fix. The fix will be cherrypicked to 3.1, too.
=> Grammar fix to Caution block in Preface Chapter

chapter-configuration.asciidoc
* Added a line regarding the added warning.  Rest of the text seems to already match what we do (did).
* Fixed a typo (in the area).
* Removed an extra whitespace (in the area).
* Removed an extra whitespace (eof).
https://issues.sonatype.org/browse/NEXUS-10209
=> NEXUS-10209-License_Improvements

chapter-pypi.asciidoc
Minor fix to Remote Storage URL for PyPi based on some user feedback.
=> Remote storage PyPi fix

chapter-bower.asciidoc
Updated.
TODO: Cherrypick to 3.1
=> Correction to instruction that user needs both URL and nexus section in bowerrc file

chapter-installation.asciidoc
Addendum to the work in JIRA: https://issues.sonatype.org/browse/NEXUS-10425
Updated nginx.conf example files with correct punctuation. Basically each directive
should end with a semicolon, even if commented out.
=> Addendum NEXUS 10425 nginx master patch

chapter-using-nexus-ui.asciidoc
In https://issues.sonatype.org/browse/NEXUS-10284 we limited the number of search results.  Updating documentation to match.
Also 114ized a line above the one I was changing=)
=> NEXUS-10284-limiting-search-results

chapter-pypi.asciidoc, chapter-rubygems.asciidoc, nexus-book-declarations.asciidoc
ADDENDUM: 3.0.2-02, it is!
Ahead of the upcoming 3.0.2 release
JIRA: https://issues.sonatype.org/browse/NEXUS-10660
In addition to the new PyPI & RubyGems chapters, updates include:
* Update *nexus-book-declarations* file; replace version-exact 3.0.1-01 with 3.0.2-01 (or whatever the correct one will be)
* Update dependency declarations for *nexus-book-examples* repo in the 3.x branch (mainly in the scripting section)
* Check book for any necessary updates per patches/fixes to be shipped with the 3.0.2 release
* Update Compatibility Matrix - https://support.sonatype.com/hc/en-us/articles/222426568-Nexus-Repository-Manager-Feature-Compatibility-Matrix
* Publish in bamboo
=> NEXUS-10660-pypi-ruby-chapter-add

chapter-upgrading.asciidoc
Uncommented RubyGems as an upgradeable format.
Addendum: Additional fix was removed per https://github.com/sonatype/nexus-book/pull/231#issuecomment-247300583. (Will update in another version or directly from the trunk.)
=> [NEXUS 10676] ruby-upgrade

chapter-installation.asciidoc
Since its deprecated until further changes occur, NEXUS-10914
Actually deleted content instead of commenting out since we dont know when (and if) it will come back. Worst case we pull this out of the git history or rewrite as agreed with @dulanism .
=> Removed documentation about installer
